images:
  - image: nginx:latest
    platform: linux/amd64
    enabled: false
    pushName: gcr.io/$PROJECT_ID/$REPO_NAME
  - image: eclipse-temurin:8u432-b06-jdk-focal
    platform: linux/amd64
    enabled: true
    pushName: eclipse-temurin:8u432-b06-jdk-focal2

dockerFiles:
  - folderPath: jdk-ffmpeg2
    enabled: false
    pushName: 111
  - folderPath: jdk-ffmpeg
    enabled: true
    pushName: 